<a href="https://colab.research.google.com/github/Je0azul5/IA-ML/blob/main/Graphlabyrinth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from IPython.display import display
from ipywidgets import Image
import ipywidgets as widgets
import time
import numpy as np
from random import randrange 
import numpy as np
import math
from collections import deque

In [2]:
class Graph():

    def __init__(self):
        self.vertex = []
        self.nodo = [[None]*0 for i in range(0)]

    #Metodo print, la cual permite imprimir la matriz
    def print(self, m, text):
        chain = ""

        for c in range(len(m)):
            chain += "\t" + str(self.vertex[c])

        chain += "\n " + ("       -" * len(m))

        for f in range(len(m)):
            chain += "\n" + str(self.vertex[f]) + " |"
            for c in range(len(m)):
                if text:
                    chain += "\t" + str(m[f][c])
                else:
                    if f == c and (m[f][c] is None or m[f][c] == 0):
                        chain += "\t" + "\\"
                    else:
                        if m[f][c] is None or math.isinf(m[f][c]):
                            chain += "\t" + "X"
                        else:
                            chain += "\t" + str(m[f][c])

        chain += "\n"
        print(chain)

    @staticmethod
    def inContent(list, k):
        if list.count(k) == 0:
            return False
        return True
    #metodo inVertice, permite saber en que vertice se encuentra
    def inVertice(self, v):
        if self.vertex.count(v) == 0:
            return False
        return True

    #metodo addVertice, permite añadir vertice
    def addVertice(self, v):
        if self.inVertice(v):
            return False
        self.vertex.append(v)
        row = cols = len(self.nodo)
        matrix_aux = [[None] * (row+1) for i in range(cols+1)]


        for f in range(row):
            for c in range(cols):
                matrix_aux[f][c] = self.nodo[f][c]
        self.nodo = matrix_aux
        return True

    #metodo addEdge, se utiliza ppara añadir nodos
    def addEdge(self, start, end, valor, aimed):
        if not(self.inVertice(start)) or not(self.inVertice(end)):
            return False
        self.nodo[self.vertex.index(start)][self.vertex.index(end)] = valor
        if not aimed:
            self.nodo[self.vertex.index(end)][self.vertex.index(start)] = valor
        return True

    #metodo nextVertice, permite pasar al siguiente vertice de la lista 
    def nextVertice(self, v):
        pos = self.vertex.index(v)
        nextList = []
        for i in range(len(self.nodo)):
            if self.nodo[pos][i] is not None:
                nextList.append(self.vertex[i])
        return nextList

    #metodo rout, muestra la ruta 
    def rout(self, k, v2):
        return self.__rout(k, v2, [])
    
    #metodo __rout, Se uiliza para recorrer los nodos y los marca como visitados
    #si fueron recorridos
    def __rout(self, k, v2, visit):
        if k == v2:
            return visit
        visit.append(k)
        next = self.nextVertice(k)
        for vertice in next:
            if not self.inContent(visit, vertice):
                if self.__rout(vertice, v2, visit):
                    print(vertice,end=' ')
                    return True
        return False
        
    #metodo depth, busqueda en profundidad
    def depth(self, inicio):
        if not self.inVertice(inicio):
            return None

        recorrido = []
        pila = [inicio]

        while len(pila) > 0:
            v_aux = pila.pop()

            if not self.inContent(recorrido, v_aux):
                recorrido.append(v_aux)

            condicion = True

            for i in range(len(self.nodo)):
                if self.nodo[self.vertex.index(v_aux)][i] is not None:
                    v_candidato = self.vertex[i]

                    # al parecer se puede reemplazar por "and not self.contenido_en(pila, v_candidato)
                    if not self.inContent(recorrido, v_candidato) and condicion:
                        # Es como un Break.
                        condicion = False

                        pila.append(v_aux)
                        pila.append(v_candidato)

        return recorrido

In [3]:
#coordenadas inicales
x=str(0)
y=str(0)

#creacion txt
tx = open("Bloqueo.txt","w")

#llenar txt 
ttx=x+"\n"+y+"\n0\n1\n0\n2\n0\n3\n0\n4\n0\n5\n1\n5\n2\n5\n3\n5\n4\n5\n5\n5\n6\n5\n7\n5\n7\n4\n7\n3\n8\n0\n7\n1\n6\n1\n5\n1\n4\n1\n3\n1\n5\n2\n5\n3\n4\n3\n3\n3\n2\n3\n9\n4\n9\n5\n9\n6\n9\n7\n8\n7\n7\n7\n6\n7\n5\n7\n4\n7\n3\n7\n1\n7\n3\n8\n5\n9\n6\n9\n9\n9"

#guardar txt
tx.write(ttx)
tx.close()




In [4]:
#Creación de listas 
inicio=[]
pared=[]
camino=[]
fin=[]

#creación de grafo
g=Graph()

#abrir txt
f = open ('Bloqueo.txt','r')

#Recorrer lista y agregar como pared
for linea in f:
  pared.append(int(linea))


fin.append(pared.pop())
fin.append(pared.pop())
inicio.append(pared.pop(0))
inicio.append(pared.pop(0))

#division de pared ya que al ingresar coordernadas X y Y se duplicaba el tamaño
total=int(len(pared)/2)
l = np.zeros((10, 10))

#Se agrega la posicion X y Y a la pared
for i in range(total):
   a=pared.pop()
   b=pared.pop()
   #print(str(a)+" "+str(b))
   l[b][a]=1

print("Imprimir matriz inicial 0 espacio vacio y 1 pared ")
print(l)


#Agregar vertices
for i in range(100):
  g.addVertice(i)


Imprimir matriz inicial 0 espacio vacio y 1 pared 
[[0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]]


In [5]:
#g.print(g.nodo,False)
g.addEdge(0, 10, 1, False)
g.addEdge(10, 20, 1, False)
g.addEdge(20, 30, 1, False)
g.addEdge(30, 40, 1, False)
g.addEdge(40, 50, 1, False)
g.addEdge(50, 60, 1, False)
g.addEdge(60, 70, 1, False)
g.addEdge(10, 11, 1, False)
g.addEdge(20, 21, 1, False)
g.addEdge(21, 22, 1, False)
g.addEdge(22, 32, 1, False)
g.addEdge(32, 42, 1, False)
g.addEdge(11, 12, 1, False)
g.addEdge(12, 13, 1, False)
g.addEdge(13, 14, 1, False)
g.addEdge(14, 24, 1, False)
g.addEdge(24, 34, 1, False)
g.addEdge(34, 44, 1, False)
g.addEdge(44, 54, 1, False)
g.addEdge(54, 64, 1, False)
g.addEdge(64, 63, 1, False)
g.addEdge(63, 62, 1, False)
g.addEdge(62, 72, 1, False)
g.addEdge(72, 82, 1, False)
g.addEdge(82, 81, 1, False)
g.addEdge(82, 92, 1, False)
g.addEdge(82, 83, 1, False)
g.addEdge(81, 91, 1, False)
g.addEdge(91, 90, 1, False)
g.addEdge(92, 93, 1, False)
g.addEdge(83, 84, 1, False)
g.addEdge(84, 85, 1, False)
g.addEdge(85, 86, 1, False)
g.addEdge(86, 76, 1, False)
g.addEdge(76, 66, 1, False)
g.addEdge(66, 56, 1, False)
g.addEdge(56, 46, 1, False)
g.addEdge(46, 36, 1, False)
g.addEdge(36, 26, 1, False)
g.addEdge(26, 16, 1, False)
g.addEdge(16, 6, 1, False)
g.addEdge(26, 27, 1, False)
g.addEdge(27, 28, 1, False)
g.addEdge(28, 18, 1, False)
g.addEdge(18, 19, 1, False)
g.addEdge(19, 29, 1, False)
g.addEdge(6, 7, 1, False)
g.addEdge(7, 8, 1, False)
g.addEdge(8, 9, 1, False)
g.addEdge(29, 39, 1, False)
g.addEdge(39, 49, 1, False)
g.addEdge(49, 48, 1, False)
g.addEdge(48, 58, 1, False)
g.addEdge(58, 68, 1, False)
g.addEdge(68, 78, 1, False)
g.addEdge(78, 79, 1, False)
g.addEdge(79, 89, 1, False)
g.addEdge(89, 88, 1, False)
g.addEdge(88, 98, 1, False)
g.addEdge(98, 99, 1, False)

#a=str(g.depth(61)[0]) 
#s=a[0:1]
#print(g.depth(99))
#g.rout(0,99)

#Imprimir matriz
print(" ")
print("Ruta")
print(g.depth(99))

 
a=[]

#Recorre el arreglo con busqueda en profundidad y al encontrar la casilla final
#se sale de este
for i in g.depth(0):
  a.append(str(i))
  if i == 99:
    break

#Imprime 1 si es pared y 2 si fue recorrido
for i in a:
  
  #print(i)
  
  if i[1:2]=='':
    #print(i[0:1]+" 0")
    l[int(0)][int(i[0:1])]=2
  
  else:
    #print(i[0:1]+" "+i[1:2])
    l[int(i[0:1])][int(i[1:2])]=2
  
  
  #print(i[0:1]+" "+i[1:2])
  #print(i)

#Imprime la matriz final
print(" ")
print("Matriz final con recorrido, 1 es pared y 2 es el recorrido")
print(l)
#print(a[:])
#print(ss[0])
#ss=[g.rout(1,61)]
#print("\033[1;33m"+"Texto en negrita color amarillo"+'\033')

 
Ruta
[99, 98, 88, 89, 79, 78, 68, 58, 48, 49, 39, 29, 19, 18, 28, 27, 26, 16, 6, 7, 8, 9, 36, 46, 56, 66, 76, 86, 85, 84, 83, 82, 72, 62, 63, 64, 54, 44, 34, 24, 14, 13, 12, 11, 10, 0, 20, 21, 22, 32, 42, 30, 40, 50, 60, 70, 81, 91, 90, 92, 93]
 
Matriz final con recorrido, 1 es pared y 2 es el recorrido
[[2. 1. 1. 1. 1. 1. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 1. 2. 1. 2. 2.]
 [0. 0. 0. 1. 2. 1. 2. 2. 2. 2.]
 [0. 1. 0. 1. 2. 1. 2. 1. 1. 2.]
 [0. 1. 0. 1. 2. 1. 2. 1. 2. 2.]
 [0. 1. 1. 1. 2. 1. 2. 1. 2. 1.]
 [0. 1. 2. 2. 2. 1. 2. 1. 2. 1.]
 [0. 1. 2. 1. 1. 1. 2. 1. 2. 2.]
 [1. 2. 2. 2. 2. 2. 2. 1. 2. 2.]
 [2. 2. 0. 0. 1. 1. 1. 1. 2. 2.]]
