<a href="https://colab.research.google.com/github/Je0azul5/AI-ML/blob/main/Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:


#Agrega las posiciones para tener el puzzle
def position(state):
   
    l = list()
    for i in state:
        indice = state.index(i)
        if indice in (0,1,2):
            l.append((i,0,state.index(i)%3))
            #print(l[:])
        if indice in (3,4,5):
            l.append((i,1,state.index(i)%3))
            #print(l[:])
        if indice in (6,7,8):
            l.append((i,2,state.index(i)%3))
            #print(l[:])                   
    return l
    


In [6]:
#Con la posicion inicial se realizan los movimientos necesarios para llegar al estado final 
def puzzle(state):
    final = (1,2,3,8,0,4,7,6,5)
    posFinal = position(final)
    estado_pos = position(state)
    t = 0
    l = list()
    for i in posFinal:
        for j in range(9):
            #if estado_pos[j][0] == i[0] and i[0]!=0:
            if estado_pos[j][0] == i[0] :
                #print('j0 =>',estado_pos[j][0],' i0=>',i[0])
                l.append(estado_pos[j][0])
                t+= abs(i[1]-estado_pos[j][1])
                t+= abs(i[2]-estado_pos[j][2])
    #print('moves: ',t)
    return l
        

In [7]:
#Creacion del txt
tx = open("Puzzle.txt","w")
tx.write("5\n4\n0\n6\n1\n8\n7\n3\n2")
tx.close()
tx = open("Puzzle.txt","r")
inp = []
table=np.zeros((3,3))
table2=np.zeros((3,3))


#llena el arreglo con los datos del txt
for i in tx:
  inp.append(int(i))

#Realiza una copia y lo modifica 
inp2 = inp.copy()
for i in range(3):
  for j in range(3):
    table[i][j]=inp.pop(0)

#Imprime el estado inical
print("Estado inicial")
print(table)
print(' ')

#Realiza la funcion puzzle la cual permite hayar el resultado
r=puzzle(inp2)

for i in range(3):
  for j in range(3):
    table2[i][j]=r.pop(0)
#muestra el resultado final
print("Estado Final")
print(table2)


Estado inicial
[[5. 4. 0.]
 [6. 1. 8.]
 [7. 3. 2.]]
 
Estado Final
[[1. 2. 3.]
 [8. 0. 4.]
 [7. 6. 5.]]
